### ISSUE TITLE
Path to mainnet

### ISSUE THREAD

**Issue by pmolina** [exactly/protocol#392]
Unsorted list of things we need to deploy in mainnet:
- [x] how many multisig addresses? e.g.: 3/5? 5/9? [Answer](https://github.com/exactly-protocol/protocol/issues/392#issuecomment-1279856850)
- [x] multisig member composition [Answer](https://github.com/exactly-protocol/protocol/issues/392#issuecomment-1261501024).
- [x] how can we estimate amount of $GRT needed? [Answer](https://github.com/exactly-protocol/protocol/issues/392#issuecomment-1279857028)
- [x] where to buy $GRT tokens? [Answer](https://github.com/exactly-protocol/protocol/issues/392#issuecomment-1279857028)
- [x] do we need $LINK tokens? how many? [Answer](https://github.com/exactly-protocol/protocol/issues/392#issuecomment-1256600146).
